/** Neutral graphite/mint product tokens, independent of corporate design systems. */
export const GUIDE_CSS = `
:root {
  color-scheme: light;
  --bg:#f4f6f7; --surface:#fdfefe; --raised:#edf2f3; --text:#1b292f;
  --muted:#51636d; --line:#d5dfe3; --accent:#126b57; --on-accent:#f8fdfb;
  --accent-soft:#e5f3ee; --warning:#805413; --warning-bg:#fbf4e4;
  --danger:#a83d37; --danger-bg:#fbefed; --scrim:#15252bb3;
  --radius:10px; --control:7px; --space:8px;
  --sans:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;
  --mono:'SFMono-Regular',Consolas,'Liberation Mono',monospace;
}
@media (prefers-color-scheme:dark) {
  :root:not([data-theme="light"]) {
    color-scheme:dark; --bg:#111618; --surface:#191f22; --raised:#222b2f;
    --text:#eff4f5; --muted:#aabac1; --line:#364249; --accent:#94dfcd;
    --on-accent:#122722; --accent-soft:#233a34; --warning:#eed393;
    --warning-bg:#352d1e; --danger:#f0ada5; --danger-bg:#352724; --scrim:#080e12bf;
  }
}
:root[data-theme="dark"] {
  color-scheme:dark; --bg:#111618; --surface:#191f22; --raised:#222b2f;
  --text:#eff4f5; --muted:#aabac1; --line:#364249; --accent:#94dfcd;
  --on-accent:#122722; --accent-soft:#233a34; --warning:#eed393;
  --warning-bg:#352d1e; --danger:#f0ada5; --danger-bg:#352724; --scrim:#080e12bf;
}
*{box-sizing:border-box}html{background:var(--bg);min-height:100%}body{margin:0;color:var(--text);font:14px/1.5 var(--sans);min-height:100dvh}
button,select{font:inherit;min-height:38px;border-radius:var(--control);border:1px solid transparent;padding:7px 13px}
button{background:var(--accent);color:var(--on-accent);font-weight:600;cursor:pointer;white-space:nowrap}
button.secondary{background:var(--surface);border-color:var(--line);color:var(--text)}
button.text-button{background:transparent;color:var(--accent);padding-inline:6px}
button:disabled{opacity:.6;cursor:not-allowed}button:active:not(:disabled){transform:translateY(1px)}
select{background:var(--surface);border-color:var(--line);color:var(--text);max-width:100%}
:focus-visible{outline:3px solid var(--accent);outline-offset:3px}a{color:var(--accent)}
h1,h2,h3,p{margin:0}h1{font-size:23px;line-height:1.3;letter-spacing:-.035em}h2{font-size:16px;line-height:1.4;letter-spacing:-.015em}h3{font-size:14px;line-height:1.5}p{overflow-wrap:anywhere}small,.caption{font-size:12px;color:var(--muted)}
.app-header{background:var(--surface);border-bottom:1px solid var(--line)}.header-inner{max-width:1304px;margin:auto;min-height:66px;padding:0 24px;display:flex;align-items:center;gap:32px}
.brand{display:flex;align-items:center;gap:10px;white-space:nowrap;font-size:15px;font-weight:700;letter-spacing:-.02em}.brand small{display:block;font-size:11px;font-weight:400;letter-spacing:0}.brand-mark{display:grid;place-items:center;width:32px;height:32px;background:var(--accent-soft);color:var(--accent);border:1px solid var(--line);border-radius:8px;font:700 12px var(--mono)}
.view-tabs{align-self:stretch;display:flex;align-items:center;gap:4px}.view-tabs button{background:transparent;color:var(--muted);min-height:42px;font-weight:550}.view-tabs button[aria-selected="true"]{color:var(--accent);background:var(--accent-soft)}
.header-tools{margin-left:auto;display:flex;align-items:center;gap:8px}.theme-label select{font-size:12px;min-height:36px;width:128px}
main{max-width:1304px;margin:auto;padding:24px 24px 16px}.page-heading{display:flex;justify-content:space-between;align-items:center;gap:16px}.page-heading p{color:var(--muted);margin-top:4px;font-size:13px}.status-line{display:flex;justify-content:space-between;gap:12px;margin:12px 0 18px;font-size:12px;color:var(--muted)}
.agent-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius)}.agent{padding:18px 20px}.agent-head{display:flex;align-items:center;gap:10px;justify-content:space-between;margin-bottom:14px}.agent-title{display:flex;align-items:baseline;gap:8px;flex-wrap:wrap}.agent-title h2{font-size:16px}.version{font:11px var(--mono);color:var(--muted)}
.pill{display:inline-flex;align-items:center;flex:none;gap:4px;max-width:100%;font-size:11px;font-weight:550;padding:3px 8px;border:1px solid var(--line);border-radius:6px;white-space:normal;color:var(--muted);background:var(--raised)}.pill.good{color:var(--accent);background:var(--accent-soft);border-color:transparent}.pill.warn{color:var(--warning);background:var(--warning-bg);border-color:transparent}
.agent-line{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:39px}.agent-line>div{min-width:0}.key{display:inline-block;min-width:88px;color:var(--muted);font-size:12px}.agent-line .text-button{font-size:12px;white-space:nowrap}.subtle-note{color:var(--muted);font-size:12px;margin-top:4px}.low-note{color:var(--warning);font-size:12px;margin:2px 0 8px}.allowance{border-top:1px solid var(--line);margin-top:10px;padding-top:10px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px 18px}.allowance.full{display:block}.allowance-entry{display:flex;justify-content:space-between;gap:8px;align-items:baseline;flex-wrap:wrap}.allowance-entry strong{font-variant-numeric:tabular-nums;font-size:14px}.allowance-entry .caption{width:100%;font-size:11px}.allowance-label{font-size:12px;color:var(--muted)}.allowance-missing{display:flex;justify-content:space-between;align-items:start;gap:10px}.allowance-missing p{font-size:12px;color:var(--muted)}.allowance-missing button{font-size:12px;flex-shrink:0;white-space:normal;max-width:155px}.context-note{font-size:12px;color:var(--muted);margin:10px 0 18px}
.section-head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:12px}.section-head p{margin-top:3px}.inline-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.inline-actions select,.inline-actions button{font-size:12px}.savings-panel{padding:18px 20px}.saving-row{display:grid;grid-template-columns:minmax(170px,1fr) minmax(180px,1fr) minmax(170px,.8fr);align-items:center;gap:20px;padding:16px 0;border-top:1px solid var(--line)}.saving-row .number{font:600 26px/1.2 var(--mono);letter-spacing:-.05em;color:var(--accent);font-variant-numeric:tabular-nums}.saving-row.negative .number{color:var(--danger)}.saving-row .amount{text-align:right}.saving-row .unit{display:block;font-size:11px;color:var(--muted);margin-top:4px}.saving-row .volume{font:12px var(--mono);color:var(--text);margin:5px 0}.saving-row .caption{display:block;margin-top:3px}.savings-footer{display:flex;justify-content:space-between;align-items:center;gap:12px;border-top:1px solid var(--line);padding-top:8px}.savings-footer button{font-size:12px}.disclosure{font-size:12px;color:var(--muted)}.disclosure>summary{padding:8px 0;cursor:pointer;list-style-position:inside}.disclosure p{padding:4px 0 8px;max-width:100ch}.empty{padding:24px 20px;background:var(--raised);border-radius:8px;color:var(--muted)}.empty h3{color:var(--text);margin-bottom:5px}.empty button{margin-top:10px}
.subtabs{display:flex;gap:6px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:12px;margin-bottom:16px;flex-wrap:wrap}.subtabs button{background:transparent;color:var(--muted);border-color:var(--line);font-size:13px}.subtabs button[aria-selected="true"]{background:var(--accent-soft);color:var(--accent);border-color:var(--accent)}
.rule{padding:16px 20px;background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);margin-bottom:10px}.rule-top{display:flex;justify-content:space-between;gap:20px;align-items:center}.rule-title{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.rule-title h3{font-size:14px}.rule-summary{color:var(--muted);font-size:13px;max-width:87ch;margin-top:5px}.rule-top>.inline-actions{flex-shrink:0}.rule-details{font-size:12px;margin-top:5px;color:var(--muted)}.rule-details>summary{display:inline-block;cursor:pointer;padding:8px 0;min-height:32px;color:var(--accent);list-style:none}.rule-details>summary::before{content:'+';margin-right:6px;font-family:var(--mono)}.rule-details[open]>summary::before{content:'-'}
.rule-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px 24px;padding-top:12px;border-top:1px solid var(--line)}.rule-detail-grid dt{color:var(--text);font-size:12px;font-weight:650;margin-bottom:4px}.rule-detail-grid dd{margin:0}.rule-detail-grid .next-step{grid-column:1/-1;background:var(--raised);padding:12px;border-radius:7px;color:var(--text)}.rule-detail-grid dl{margin:0}.rule-mode{font-size:11px;color:var(--muted);padding-top:8px}.rule-intro{color:var(--muted);font-size:13px;margin-bottom:12px}
#view-activity>.panel{padding:18px 20px}.activity-row{display:grid;grid-template-columns:85px 1fr;gap:18px;padding:13px 0;border-top:1px solid var(--line)}.activity-row time{font:11px var(--mono);color:var(--muted)}.activity-row p{font-size:13px}.activity-row.attention p{color:var(--warning)}
.notice,.error{border:1px solid var(--line);border-left:3px solid var(--warning);border-radius:7px;background:var(--warning-bg);padding:10px 12px;font-size:13px;margin:10px 0;color:var(--text)}.error{border-left-color:var(--danger);background:var(--danger-bg)}#notices details{margin-bottom:14px}#notices summary{cursor:pointer;color:var(--warning);font-weight:550;padding:8px 0;font-size:13px}#notices p{margin-top:4px}.notice-row{padding:8px 0;border-top:1px solid var(--line)}
footer{margin-top:20px;padding:12px 0 0;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:11px}
dialog{background:var(--surface);color:var(--text);border:1px solid var(--line);border-radius:12px;max-width:620px;width:calc(100% - 32px);max-height:88dvh;padding:0}dialog::backdrop{background:var(--scrim)}.dialog-body{padding:24px}.dialog-heading{margin-bottom:16px}.dialog-heading h2{font-size:19px}.dialog-actions{display:flex;justify-content:flex-end;gap:10px;flex-wrap:wrap;margin-top:22px;border-top:1px solid var(--line);padding-top:16px}#review-content p{margin-bottom:12px;font-size:13px}#task-form label{display:block;font-size:12px;font-weight:600;margin:12px 0 5px}#task-form select{width:100%}.checklist{padding-left:20px;font-size:13px}.checklist li{margin:12px 0}.checklist p{color:var(--muted);margin-top:4px}.help-steps{padding-left:20px;color:var(--text);font-size:13px}.help-steps li{padding-left:4px;margin:10px 0}.command-box{border:1px solid var(--line);background:var(--raised);border-radius:7px;padding:12px;display:flex;gap:10px;align-items:center;justify-content:space-between}.command-box code{font:12px/1.6 var(--mono);overflow-wrap:anywhere;white-space:pre-wrap}.command-box button{font-size:12px;flex-shrink:0}.command-context{font-size:12px;color:var(--muted);margin:14px 0 5px}.help-refresh{margin-top:12px}.help-refresh button{font-size:12px}.read-only-box{padding:12px;background:var(--raised);border-radius:7px;margin-bottom:12px}.read-only-box strong{display:block;margin-bottom:5px}.copy-fallback{width:100%;margin-top:8px;background:var(--raised);color:var(--text);font:12px var(--mono);padding:8px;border:1px solid var(--line)}
.sr-only{position:absolute!important;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.skip{position:absolute;left:-9999px;top:0}.skip:focus{left:16px;top:8px;background:var(--surface);padding:12px;z-index:2}.skeleton{height:220px;background:var(--raised)}[hidden]{display:none!important}
@media(hover:hover){button.secondary:hover:not(:disabled),.view-tabs button:hover,.subtabs button:hover{background:var(--raised)}button.text-button:hover:not(:disabled){text-decoration:underline}button:not(.secondary):not(.text-button):hover:not(:disabled){filter:brightness(.96)}}
@media(max-width:1000px){.header-inner{gap:16px}.theme-label{display:none}.saving-row{gap:12px}.key{min-width:72px}.agent{padding:16px}.agent-head{align-items:flex-start}.agent-line{flex-wrap:wrap;gap:4px}.allowance{grid-template-columns:1fr 1fr}}
@media(max-width:720px){.header-inner{padding:12px 16px;flex-wrap:wrap;min-height:0;gap:10px}.header-tools{order:1}.brand{order:0}.view-tabs{order:2;flex-basis:100%;justify-content:space-between;gap:4px}.view-tabs button{flex:1;padding:8px;font-size:13px}.brand small{display:none}main{padding:18px 16px 12px}.page-heading{align-items:flex-start;gap:8px}h1{font-size:21px}.page-heading p{font-size:12px;max-width:29ch}.page-heading>button{font-size:12px;padding:8px 12px}.status-line{margin:10px 0 14px}.status-line .caption{display:none}.agent-grid{grid-template-columns:1fr;gap:12px}.agent-head{align-items:center}.agent-line{flex-wrap:nowrap}.key{min-width:83px}.context-note{margin-bottom:14px}.savings-panel{padding:16px}.section-head{align-items:flex-start;gap:12px;flex-wrap:wrap}.section-head>.inline-actions{width:100%;justify-content:space-between}.saving-row{grid-template-columns:1fr auto;gap:5px 10px;padding:14px 0}.saving-row .breakdown{grid-column:1;grid-row:2}.saving-row .amount{grid-column:2;grid-row:1/3;max-width:145px}.saving-row .number{font-size:23px}.saving-row .caption{font-size:11px}.savings-footer{align-items:start;flex-direction:column;gap:0}.rule{padding:14px}.rule-top{align-items:flex-start;flex-direction:column;gap:10px}.rule-top>.inline-actions{width:100%}.rule-detail-grid{grid-template-columns:1fr;gap:12px}.rule-detail-grid .next-step{grid-column:auto}.rule-title{gap:6px}.activity-row{grid-template-columns:62px 1fr;gap:8px}footer{flex-direction:column;gap:4px}.dialog-body{padding:18px}.command-box{flex-direction:column;align-items:stretch}.command-box button{align-self:flex-start}.allowance-missing{flex-direction:column;gap:4px}.allowance-missing button{max-width:none}.theme-label{display:block}.theme-label select{width:116px}button,select,.rule-details>summary{min-height:44px}}
@media(max-width:380px){.theme-label{display:none}.agent-title{gap:4px}.pill{font-size:10px}.agent-line{flex-wrap:wrap}.page-heading>button{padding:8px}.view-tabs button{font-size:12px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}button:active{transform:none}}
@media(forced-colors:active){button,.panel,.rule,.pill{border:1px solid CanvasText}:focus-visible{outline:2px solid Highlight}}
`;
